### ISSUE TITLE
Support nullable properties

### ISSUE THREAD

**Issue by kirillcisco** [kevinLay7/RocketLeagueTracker#2]
After adding a user with the nickname OoSl (idk why, maybe problem with API answer), the app crashes.

Newtonsoft.Json.JsonSerializationException: "Error converting value {null} to type 'System.DateTimeOffset'. Path 'data.metadata.lastUpdated.value', line 1, position 520."

ArgumentException: Could not cast or convert from {null} to System.DateTimeOffset.

![изображение](https://user-images.githubusercontent.com/26303339/94145579-6e1c4380-fe7b-11ea-985e-9fcde99d0da8.png)

**Comment by kevinLay7** [comment]
Good catch.  Their API is having issues right now, so not all data is being returned.  I think this might be caused from that, but they needed to be nullable anyways.
